apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
  - name: metrics
    targetPort: 9090
    port: 9090
    protocol: TCP
